security:
  oauth2:
    client:
      clientId: 1033577033339-e23g9k2l5easqv4g146org7l19c3co9e.apps.googleusercontent.com
      clientSecret: dNjSvkO9oPKFqe87_EMbDyEN
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?hd=nearsoft.com
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
